language: java
jdk:
#  - openjdk7
  - oraclejdk7
#  - openjdk6

notifications:
  email: true

    
env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "qYMMVekEh7QlCKO0QY8/3DP4q2nYjarb4qo8/fn+jUDudO3S1ZK5oVjpLVEk1+DQMKYb8Idyh6eobWrcnaNvfLtA8tZbOt0ByCp6tDCXiKLSTccQR1amY50Luh3XVA5mRdeWFuPL3LzJl8/pR/rjx8vZvPS3Fo3swlYeKzhNaAg="
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_SDKS=android-19,build-tools-19.0.3,sysimg-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19  ANDROID_SDKS=android-19,build-tools-19.0.3,sysimg-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=x86
#    - ANDROID_TARGET=android-19  ANDROID_SDKS=android-19,build-tools-19.0.3,addon-google_apis-google-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=armeabi-v7a
#    - ANDROID_TARGET=android-19  ANDROID_SDKS=android-19,build-tools-19.0.3,addon-google_apis_x86-google-19 ANDROID_BUILD_TOOLS_VERSION=19.0.3 ANDROID_ABI=x86
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget https://dl.google.com/android/android-sdk_r22.3-linux.tgz
    - tar xzf android-sdk_r22.3-linux.tgz
#    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export ANDROID_HOME=`pwd`/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION

    
    # Install required Android components.
    - android list sdk --extended
    - android list target
    - android list sdk --extended -a

    # Do you accept the license 'android-sdk-license-bcbbd656' [y/n]:
    - echo y | android update sdk --filter platform-tool,extra-android-support,${ANDROID_SDKS} --no-ui --force

    # PROVISIONAL: changed SDKr22 build-tools path. create symbolic link
#    - if [ ! -e ${ANDROID_HOME}/platform-tools/aapt ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/aapt ${ANDROID_HOME}/platform-tools/aapt; fi
#    - if [ ! -e ${ANDROID_HOME}/platform-tools/aidl ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/aidl ${ANDROID_HOME}/platform-tools/aidl; fi

    # Create and start emulator
    - export AVD_NAME=test
    - echo no | android create avd --force -n ${AVD_NAME} -t ${ANDROID_TARGET} --abi ${ANDROID_ABI}
    - emulator -avd ${AVD_NAME} -no-skin -no-audio -no-window &

before_script:
    # Make sure the emulator has started before running tests
    - chmod +x ./wait_for_emulator
    - ./wait_for_emulator
#    - adb wait-for-device 

addons:
  coverity_scan:
    project:
      name: "cafedeaqua/PotatotipsVendingMachine"
      description: "Your project description here"
    notification_email: cafedeaqua@gmail.com
    build_command_prepend: ant -f build.xml emma debug install
    build_command: ant -f tests/build.xml emma debug install test
    branch_pattern: coverity_scan

script:
 - ant -f build.xml emma debug install
 - ant -f tests/build.xml emma debug install test
 - ls -la /home/travis/build/cafedeaqua/PotatotipsVendingMachine/tests/bin
 - adb pull /data/data/com.andbrowser.potatotipsvendingmachine/coverage.ec .
 - ls -la .
 
 


